Data/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include 

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('Page.urls')),
    url(r'^news', include('news.urls')),
    url(r'^book', include('book.urls')),
]

Page/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include 

from django.views.generic import ListView, DetailView

from . import views
from . models import Person

urlpatterns = [
    
    url(r'^', views.index),
    
]

book/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include 

from django.views.generic import ListView, DetailView

from . import views


urlpatterns = [
    
    url(r'^', views.index),
    url(r'^books/$', views.BookListView.as_view(), name='books'),
]

news/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include 

from . import views
from news.models import Articles

from django.views.generic import ListView, DetailView

urlpatterns = [
    
    url(r'^', views.index),
    url(r'^$', ListView.as_view(queryset=Articles.objects.all(),
    template_name="news/news.html"
    )),
    
]

Page/models.py
from django.db import models
from django.db.models import Model
from django import forms

class Person(models.Model):
    
    name = models.CharField(max_length=20)
    age = models.IntegerField()



    def __str__(self):
        return self.name

book/models.py
from django.db import models

# Create your models here.
class book(models.Model):
    
    
    name = models.CharField(max_length=20)
    age = models.IntegerField()



    def __str__(self):
        return self.name

news/models.py
from django.db import models
from django.db.models import Model
from django import forms

# Create your models here.
class Articles(models.Model):
    title = models.CharField(max_length = 120)
    post = models.TextField()
    date = models.DateTimeField(
        verbose_name=("Creation date"), 
    )

    def __str__(self):
        return self.title

Page/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'page/page.html')

book/views.py
from django.shortcuts import render
from django.views import generic 

from book.models import book

def index(request):
    return render(request, 'book/book.html')

class BookListView(generic.ListView):
    model = book

    def get_queryset(self):
        return Book.objects.filter(title__icontains='war')[:5]

    def get_context_data(self, **kwargs):
        
        context = super(BookListView, self).get_context_data(**kwargs)
        
        context['some_data'] = 'This is just some data'
        return context

news/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'news/news.html')

Page/templates/page/page.html
{% extends 'page/wrapper.html' %}

{% block title %}
    Главная страница
{% endblock %}

{% block body %}
<h2>Hello, write login </h2>
<h2>and password</h2>
<div>
<input type="text" name="username" placeholder="Username">
<br />
<br />
<input type="password" name="password" placeholder="password">
<br />
<br />
<input type="submit" value="Готово">
<br />
<br />
<button><a href="news">news</a></button>
<button><a href="admin">admin</a></button>
<button><a href="book">book</a></button>
</div>
<br />
<br />
<input type="text" name="typenews" placeholder="Type of news">
<br />
<br />
<input type="text" name="titlenews" placeholder="Title news">
<br />
<br />
<input type="text" name="postnews" placeholder="postnews">
<br />
<br />
<input type="button" type="submit" value="Создать пост">
{% endblock %}

book/templates/book/book.html
{% extends 'book/wrapper.html' %}


{% block title %}
 book страница 
{% endblock %}



{% block body %}
<h2>
    Тут будут находитсья посты 
</h2>

<button><a href="news">news</a></button>
<button><a href="admin">admin</a></button>
<button><a href="book">book</a></button>

<h1>Book List</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %} 

{% endblock %}

book/templates/book/wrapper.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}

        {% endblock %}
    </title>
</head>
<body>
    {% block body %}

    {% endblock %}
</body>
</html>

news/templates/news/news.html
{% extends 'news/wrapper.html' %}
  {% block title %}
        Страница Новостей
  {% endblock %}


  {% block body %}
  <h1>hi</h1>

  <button><a href="./../page">page</a></button>
  <button><a href="./../admin">admin</a></button>
 
  {% for news in object_list %}
  <h1>
        <a href='/news/{{post.id}}'>{{post.title}}</a>
        {{post.post}}
        {{post.date}}
  </h1>
  {% endfor %}

      <h1>Block end</h1> 

  {% endblock %}

  

news/templates/news/wrapper.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}

        {% endblock %}
    </title>
</head>
<body>
    {% block body %}

    {% endblock %}
    <br />
    {% block footer %}

    {% endblock %}

</body>
</html>